# Generated by Django 4.1.1 on 2022-09-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventsAttending',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('beyond_the_horizon', models.BooleanField(default=False)),
                ('workshop_1', models.BooleanField(default=False)),
                ('workshop_2', models.BooleanField(default=False)),
                ('workshop_3', models.BooleanField(default=False)),
                ('workshop_4', models.BooleanField(default=False)),
                ('workshop_5', models.BooleanField(default=False)),
                ('workshop_6', models.BooleanField(default=False)),
                ('standup', models.BooleanField(default=False)),
                ('game_night', models.BooleanField(default=False)),
                ('student_alumni_mentorship', models.BooleanField(default=False)),
                ('coming_full_circle', models.BooleanField(default=False)),
                ('ypo', models.BooleanField(default=False)),
                ('tedx', models.BooleanField(default=False)),
                ('ceo_connect', models.BooleanField(default=False)),
                ('speed_mentoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMentoringTopics',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mi_gd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
                ('pref3', models.CharField(default=False, max_length=100)),
                ('date', models.CharField(default=False, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('events', models.ManyToManyField(related_name='events', to='home.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
