# Generated by Django 4.0.7 on 2022-10-01 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventsAttending',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('beyond_the_horizon', models.BooleanField(default=False)),
                ('it_software', models.BooleanField(default=False)),
                ('consulting', models.BooleanField(default=False)),
                ('analytics', models.BooleanField(default=False)),
                ('quant', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('product_management', models.BooleanField(default=False)),
                ('standup', models.BooleanField(default=False)),
                ('game_night', models.BooleanField(default=False)),
                ('student_alumni_mentorship', models.BooleanField(default=False)),
                ('coming_full_circle', models.BooleanField(default=False)),
                ('ypo', models.BooleanField(default=False)),
                ('tedx', models.BooleanField(default=False)),
                ('ceo_connect', models.BooleanField(default=False)),
                ('speed_mentoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='groupm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMentoringTopics',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='mi_gd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(default=False, max_length=100)),
                ('date', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
                ('pref3', models.CharField(default=False, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='speedm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('rollno', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('p_email', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
