# Generated by Django 4.0.7 on 2022-09-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_1',
            new_name='analytics',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_2',
            new_name='consulting',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_3',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_4',
            new_name='it_software',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_5',
            new_name='product_management',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_6',
            new_name='quant',
        ),
    ]
