# Generated by Django 4.1.1 on 2022-09-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mi_gd',
            old_name='mode',
            new_name='interest',
        ),
    ]
