# Generated by Django 4.1.1 on 2022-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_mode_mi_gd_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='speedm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
