# Generated by Django 4.1.1 on 2022-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_events_profile_contact_profile_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_question', models.CharField(max_length=100)),
            ],
        ),
    ]
