# Generated by Django 4.1.1 on 2022-10-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_groupm_speedm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_gd',
            name='core_field',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
