# Generated by Django 4.1.1 on 2022-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mi_gd_core_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='migd',
            fields=[
                ('rollno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('interest', models.CharField(default='', max_length=100)),
                ('pref1', models.CharField(default='', max_length=100)),
                ('pref2', models.CharField(default='', max_length=100)),
                ('pref3', models.CharField(default='', max_length=100)),
                ('dateAvailable', models.CharField(default='', max_length=100)),
                ('coreField', models.CharField(default='', max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='shadowPrograme',
            fields=[
                ('rollno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='paymentProof')),
            ],
        ),
        migrations.RenameModel(
            old_name='speedm',
            new_name='speedMentoring',
        ),
        migrations.DeleteModel(
            name='mi_gd',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_1',
            new_name='analytics',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_2',
            new_name='consulting',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_3',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_4',
            new_name='it_software',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_5',
            new_name='product_management',
        ),
        migrations.RenameField(
            model_name='eventsattending',
            old_name='workshop_6',
            new_name='quant',
        ),
        migrations.AddField(
            model_name='groupmentoringtopics',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventsattending',
            name='roll_no',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
