# Generated by Django 4.1.1 on 2022-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mi_gd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default=False, max_length=100)),
                ('pref1', models.CharField(default=False, max_length=100)),
                ('pref2', models.CharField(default=False, max_length=100)),
                ('pref3', models.CharField(default=False, max_length=100)),
                ('date', models.CharField(default=False, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
            ],
        ),
    ]
