# Generated by Django 4.1.1 on 2022-09-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_gd',
            name='resume',
            field=models.FileField(blank=True, upload_to='https://drive.google.com/drive/folders/1dVtx-HR0CeLcsuVxWtQFwiesM4KI223q?usp=sharing'),
        ),
    ]
