# Generated by Django 4.1.1 on 2022-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_gd', '0002_alter_mi_gd_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_gd',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
